### ISSUE TITLE
ModuleNotFoundError: No module named 'rtlib'

### ISSUE THREAD

**Issue by lgatto** [SlavovLab/DART-ID#3]
Followin up from issue #2 and after installing the `Tkinter` module, I have the following missing module
```
$ dart_id                    
Traceback (most recent call last):
  File "/home/lgatto/.local/bin/dart_id", line 7, in <module>
    from dart_id.update import main
  File "/home/lgatto/.local/lib/python3.7/site-packages/dart_id/update.py", line 15, in <module>
    from dart_id.figures import figures
  File "/home/lgatto/.local/lib/python3.7/site-packages/dart_id/figures.py", line 16, in <module>
    from dart_id.figure_gen import *
  File "/home/lgatto/.local/lib/python3.7/site-packages/dart_id/figure_gen/exp_alignment.py", line 9, in <module>
    from rtlib.helper import *
ModuleNotFoundError: No module named 'rtlib'
```

**Comment by blahoink** [comment]
I just pushed another fix changing the module names. Hopefully an uninstall/re-install does the trick. Sorry again for the troubles.

**Comment by lgatto** [comment]
Success!
```
$ dart_id -h
usage: dart_id [-h] [-i INPUT [INPUT ...]] [-o OUTPUT] [-v] [--version] -c
               CONFIG_FILE

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT [INPUT ...], --input INPUT [INPUT ...]
                        Input file(s) from search engine
  -o OUTPUT, --output OUTPUT
                        Path to output data. Default: None
  -v, --verbose
  --version             Display the program's version
  -c CONFIG_FILE, --config-file CONFIG_FILE
                        Path to config file. See example/config_example.yaml
```
I'll try to run it properly next week. Thank you for your prompt support.
