### ISSUE TITLE
'fido_network' object has no attribute 'node'

### ISSUE THREAD

**Issue by benni93** [SlavovLab/DART-ID#7]
I get the following error after optimization. Windows 10 and Python 3.7.3. Installed with pip. Sorry for the bad formatting.

`
Optimization terminated normally:
  Convergence detected: absolute parameter change was below tolerance
Traceback (most recent call last):
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\AppData\Local\Continuum\miniconda3\Scripts\dart_id.exe\__main__.py", line 9, in <module>
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\site-packages\dart_id\update.py", line 484, in main
    df_adjusted = run_internal(df_adjusted, parameter_map)
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\site-packages\dart_id\fido\BayesianNetwork.py", line 1007, in run_internal
    fn.load_from_dataframes([df], **parameter_map)
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\site-packages\dart_id\fido\BayesianNetwork.py", line 761, in load_from_dataframes
    self = bayesian_network_union(self, sub_fn)
  File "c:\users\me\appdata\local\continuum\miniconda3\lib\site-packages\dart_id\fido\BayesianNetwork.py", line 176, in bayesian_network_union
    bn1.add_node(bn2.get_node_from_id(i), **bn2.node[i])
AttributeError: 'fido_network' object has no attribute 'node'
`

**Comment by blahoink** [comment]
Hi,

Would you mind sending your configuration file (just the `.yml` file, no need to send the input data) so I can try to reproduce the error with the options you set?

Thanks,
Albert

**Comment by benni93** [comment]
I used this config file (without .txt, github does not support upload of .yaml) 
[config_annotated.yaml.txt](https://github.com/SlavovLab/DART-ID/files/3882585/config_annotated.yaml.txt)
 with this command:

`dart_id.exe -c C:\Users\me\Documents\Dart-ID_test\config_annotated.yaml -o C:\Users\me\Documents\Dart-ID_test\output -i C:\Users\me\Documents\Dart-ID_test\MQ_output\combined\txt\evidence.txt`

**Comment by blahoink** [comment]
Thanks for the config file. I'm unable to find any issues with the fido network in the windows version on my end. How are you managing your python installation? (anaconda/miniconda, downloaded off python website)

If you're using conda, can you run `conda list --explicit` so I can replicate your environment?

**Comment by benni93** [comment]
conda list --explicit does not show the pip packages. I just uploaded my complete process in terminal. Can you replicate this?

[terminal_output.txt](https://github.com/SlavovLab/DART-ID/files/3896163/terminal_output.txt)

**Comment by blahoink** [comment]
I was able to reproduce the error and fix it by reverting to networkx=2.2. You can fix yourself this by running:

`conda install networkx=2.2`

Let me know if that works for you

I suspect I have some legacy python2 snippets floating around (since the `fido/` code was originally written in Python 2). For now I will update the dependency list to address this.

**Comment by benni93** [comment]
Works! Thank you!
